Format pack price and pack premium
timcu/sas-select pull request #30
Opened 2019-07-13 14:01 UTC by chayawit

This fixes issue https://github.com/timcu/sas-select/issues/18.

I tried to follow this doc but not sure how to update the filter dicts.
http://jinja.pocoo.org/docs/2.10/api/#custom-filters

I'm actually not sure if we were supposed to allow None value in the db for Pack Premium.

2019-07-14 05:34 UTC, timcu requested changes
I was expecting the change to be made only in the html templates. However, this can work also. This has the advantage of handling negative amounts although I am pretty sure all our prices will be positive. I don't like your use of isinstance(products, (list,)). In Python they favour ducktyping rather than explicit typing. In your solution it will work for a list but not for a tuple or a set or some other user defined sequence of database records. The only reason you are doing it is so you can use the same function for the single product as the list of products. However, you have then created another function anyway format_one_product(). I would create two functions currency_format_one(product) and currency_format_all(products) because the user is going to know whether they are passing one or many products. currency_format_all can then call currency_format_one for each one.
Also I don't like replacing an existing value of one type with another value of another type. Future versions of this code may add up all the prices of the items selected. Once you have called your function, we would need to convert from formatted strs back to floats to do the calculations. A better solution would be to create new keys eg PackPriceFormatted and PackPremiumFormatted in the same dictionary. 
I don't like the fact that 'id' changed to 'ID'. I am not sure where that happened.
I think to convert from Sqlite Row to dict you can just use dict(product)

2019-07-14 16:42 UTC, chayawit commented
Hi, Tim. Thank you for your feedback.

I first wanted to make just a string formatting with jinja too, but then realised some Pack Premiums are `None` or negative values. Please search company code 3133 for an example of negative Pack Premium. I couldn't find an easy way to solve.

Now I finally have found how to change in html file only but it would read
`{{ "None" if product.PackPrice is none else "${:0,.2f}".format(product.PackPrice) if product.PackPrice >= 0 else "-${:0,.2f}".format(product.PackPrice|abs) }}`
, which is pretty long and seems like too much logic to put in the view?

If we stick to changing in init file, I agree with your strategy to split the nested functions and also adding new keys rather than modifying old keys.

The reason I have to change id to ID is that column name is actually `ID` in the schema. `id` used to work fine because `Row` allows case insensitivity, but dict doesn't.

I actually just have a new idea. Instead of changing to dict, we can keep Row intact and pass prices as 2 additional string arguments to `render_template` for product view page, or a list of tuple for product list page. With this approach, we don't need to change id to ID.

2019-07-14 23:51 UTC, timcu commented
Thanks for your response. 

1. As ID is in the schema we should use ID throughout. I hadn't realised Row was case insensitive.

2. Good to know there are some negative premiums. I am not sure what a negative premium means but you are right in that we have to display a negative price. I also agree with you that we should try to keep excessive logic out of the templates. Maybe a jinja2 filter is a good way to do it. See https://flask.palletsprojects.com/en/1.1.x/templating/ . They even give an example of price formatting using a template context but they say a filter would be another good way of doing this.

2019-07-15 02:35 UTC, chayawit commented
```py
    @app.template_filter()
    def format_price(price):
        if price is None:
            return None
        elif price >= 0:
            return '${:,.2f}'.format(price)
        else:
            return '-${:,.2f}'.format(abs(price))

```
I have tried adding this to init.py and it works fine. I'm trying to revert the last commits of this branch and apply the new change. If it doesn't work, I will create a new branch instead.

2019-07-15 03:52 UTC, timcu commented
Looks good. Not important, but if price is None I would return a dash or a zero, or an empty str.

2019-07-16 01:39 UTC, chayawit commented
Should I use git revert or is it ok to use git reset? Or maybe a new branch altogether?

2019-07-16 01:46 UTC, timcu commented
I actually have never used git reset or git revert so feel free to experiment. As long as no-one else has forked your branches you can do whatever you want.

Personally I think this will be such a different pull request it should go in its own branch. This also makes it easy to compare the new way with the old.

2019-07-16 02:06 UTC, chayawit commented
Ok. I will create a new branch.

2019-07-16 02:06 UTC, closed without merging