Record excel files reading in DB
timcu/sas-select pull request #48
Opened 2019-08-07 03:54 UTC by chayawit

Fixes issue #44.

Please note that excel version is read from database every time `listproducts.html` or `viewproduct.html` is rendered.

Maybe in the future we could add a file in instance path to keep the latest excel file name and scrape date so the templates can read from it rather than from the database. Then, update the file when a new scrape is made.

2019-08-08 23:35 UTC, timcu requested changes
I have read that autoincrement should be avoided in sqlite if not absolutely required so please remove from schema. 

https://sqlite.org/autoinc.html

2019-08-08 23:57 UTC, timcu commented
Please add a comment describing your regular expression search

    file_name = re.search(r'([^/]+)(?=\.\w+$)', new_url).group(0)

Are you looking for the group of one or more characters which do not include a forward slash and the group is followed by either a question mark or equals sign or full stop or white space or plus sign or end of line?

2019-08-09 01:37 UTC, timcu commented
Rather than passing `excel=datasheet.find_last_file_name()` into every call to `render_template`, you could create a `context_processor` (in the same place you have created `template_filter`)

    @app.context_processor
    def inject_excel_file_name():
        return dict(excel=datasheet.find_last_file_name())

2019-08-09 02:17 UTC, chayawit commented
> Please add a comment describing your regular expression search
> 
> ```
> file_name = re.search(r'([^/]+)(?=\.\w+$)', new_url).group(0)
> ```
> 
> Are you looking for the group of one or more characters which do not include a forward slash and the group is followed by either a question mark or equals sign or full stop or white space or plus sign or end of line?

You were right about excluding forward slashes.

`?=` means positive lookahead. `w` is an alphanumeric character. `+` means matching between one or more.

So `(?=\.\w+$)` means "look ahead to find a dot, followed by a word, follow by end of line and exclude this whole part."

The expression gives the excel file name without its extension.

You can try `([^\/]+)(?=\.\w+$)` with `https://www.health.gov.au/internet/main/publishing.nsf/Content/AB1C0973EEA98E14CA257BF0001E01C4/$File/sas-schedule-1-july-2019-full.xls` on  https://regexr.com/.

2019-08-09 02:21 UTC, chayawit commented
Should I make a new branch or can I push more commits to this one and you will compress them together later?

2019-08-09 02:59 UTC, timcu commented
Now that the URL /init-db is not doing a full initialisation of the database, maybe it should be called something else, like /fetch-data. That way it won't get confused with the command line init-db which now creates two empty tables. Alternatively, /init-db from a URL should create tbl_data_reading if it doesn't exist yet.

2019-08-09 03:06 UTC, timcu commented
> Should I make a new branch or can I push more commits to this one and you will compress them together later?

Push more commits to the same branch

2019-08-09 03:08 UTC, timcu commented
> So (?=\.\w+$) means "look ahead to find a dot, followed by a word, follow by end of line and exclude this whole part."

Ah I see now. Yes please add a comment describing the intention of the re. I was way off!

2019-08-09 04:44 UTC, chayawit commented
> > So (?=.\w+$) means "look ahead to find a dot, followed by a word, follow by end of line and exclude this whole part."
> 
> Ah I see now. Yes please add a comment describing the intention of the re. I was way off!

Do I explain in detail or just the final result?

2019-08-09 05:02 UTC, timcu commented
Enough that when you are looking at your own code in ten years time and you haven't used regular expressions in that time that you will still be able to work out what is happening. :) I would put in what I was trying to achieve and then how I am doing it

    # Find excel file name from end of url excluding final .xls or .xlsx
    # ([^\/]+) : Find group of characters not including forward slash
    # (?=.\w+$) : look ahead to find a dot, followed by a word, follow by end of line and exclude this whole part.

2019-08-09 06:45 UTC, timcu approved these changes

2019-08-09 06:48 UTC, merged